export const ADD_NOTIFICATION_ERROR = 'ADD_NOTIFICATION_ERROR';
export const REMOVE_NOTIFICATION_ERROR = 'REMOVE_NOTIFICATION_ERROR';
export const REMOVE_ALL_NOTIFICATIONS_ERROR = 'REMOVE_ALL_NOTIFICATIONS_ERROR';
export const SET_NOTIFICATION_AS_READED_ERROR = 'SET_NOTIFICATION_AS_READED_ERROR';
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';
